version: '3.8'

services:

  # ── Load Balancer ─────────────────────────────────────────
  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - server1
      - server2
      - server3

  # ── Chat Server instances ──────────────────────────────────
  server1:
    build: ./server
    environment:
      PORT: 3000
      SERVER_ID: server-1
      MONGO_URI: mongodb://mongo:27017/chatapp
      REDIS_HOST: redis
      REDIS_PORT: 6379
    depends_on:
      - mongo
      - redis

  server2:
    build: ./server
    environment:
      PORT: 3000
      SERVER_ID: server-2
      MONGO_URI: mongodb://mongo:27017/chatapp
      REDIS_HOST: redis
      REDIS_PORT: 6379
    depends_on:
      - mongo
      - redis

  server3:
    build: ./server
    environment:
      PORT: 3000
      SERVER_ID: server-3
      MONGO_URI: mongodb://mongo:27017/chatapp
      REDIS_HOST: redis
      REDIS_PORT: 6379
    depends_on:
      - mongo
      - redis

  # ── Redis ──────────────────────────────────────────────────
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"   # expose để debug từ host

  # ── MongoDB ────────────────────────────────────────────────
  mongo:
    image: mongo:7
    ports:
      - "27017:27017" # expose để dùng MongoDB Compass
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data:
