events {
    worker_connections 1024;
}

http {
    # Danh sách các Chat Server
    upstream chat_servers {
        ip_hash;

        server server1:3000 max_fails=3 fail_timeout=10s;
        server server2:3000 max_fails=3 fail_timeout=10s;
        server server3:3000 max_fails=3 fail_timeout=10s;

    }

    server {
        listen 80;

        location / {
            root /usr/share/nginx/html;
            index index.html;
            try_files $uri $uri/ =404;
        }

        location /socket.io/ {
            proxy_pass         http://chat_servers;

            
            proxy_http_version 1.1;
            proxy_set_header   Upgrade    $http_upgrade;
            proxy_set_header   Connection "upgrade";

            proxy_set_header   Host            $host;
            proxy_set_header   X-Real-IP       $remote_addr;
            proxy_set_header   X-Forwarded-For $proxy_add_x_forwarded_for;

            proxy_read_timeout  3600s;
            proxy_send_timeout  3600s;

            proxy_connect_timeout 5s;

            proxy_next_upstream error timeout invalid_header http_502 http_503 http_504;
            proxy_next_upstream_tries 2;
            proxy_next_upstream_timeout 10s;
        }

        location /api/ {
            proxy_pass       http://chat_servers;
            proxy_set_header Host            $host;
            proxy_set_header X-Real-IP       $remote_addr;

            proxy_connect_timeout 5s;
            proxy_next_upstream error timeout invalid_header http_502 http_503 http_504;
            proxy_next_upstream_tries 2;
        }

        location /health {
            proxy_pass       http://chat_servers;
        }
    }
}